version: '3.8'
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: msps-db_owner
      POSTGRES_PASSWORD: Lz0aHmKt9Bhs
      POSTGRES_DB: msps-db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U msps-db_owner -d msps-db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: akhil18133/magic-square-backend-image:latest
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: postgresql://msps-db_owner:Lz0aHmKt9Bhs@db/msps-db
      SQLALCHEMY_TRACK_MODIFICATIONS: "False"
      JWT_SECRET_KEY: akhil-secret-key
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: akhil18133/magic-square-frontend-image:latest
    ports:
      - "3000:80"

volumes:
  postgres_data:
