version: '3.8'
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: msps-db_owner
      POSTGRES_PASSWORD: Lz0aHmKt9Bhs
      POSTGRES_DB: msps-db
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: postgresql://msps-db_owner:Lz0aHmKt9Bhs@db/msps-db
      SQLALCHEMY_TRACK_MODIFICATIONS: "False"
      JWT_SECRET_KEY: akhil-secret-key
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:80"

volumes:
  postgres_data:
