version: '3.8'
services:
  frontend:
    build: 
      context: ./frontend # This tells Docker where to find the Dockerfile and source code for the frontend
    ports:
      - "3000:80"
  backend:
    build: 
      context: ./backend # This is crucial, it points to the directory containing your backend Dockerfile and requirements.txt
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: msps-db_owner
      POSTGRES_PASSWORD: Lz0aHmKt9Bhs
      POSTGRES_DB: msps-db
    ports:
      - "5432:5432"
